from __future__ import annotations

from typing import Any

MANIFEST: dict[str, Any] = {'schema_version': 1,
 'artifact_contracts': ['sfmapi.radiance.snapshot.v1',
                        'sfmapi.radiance.variant.ply.v1',
                        'sfmapi.radiance.metrics.v1'],
 'backend_actions': ['lfs.*'],
 'capabilities': ['radiance.train',
                  'radiance.evaluate',
                  'radiance.metrics.psnr',
                  'radiance.metrics.ssim'],
 'compatibility': {'cuda': 'required',
                   'os': ['windows', 'linux'],
                   'python': '>=3.12,<3.13',
                   'sfmapi': '>=0.0.1',
                   'torch': None},
 'config_schemas': ['radiance.train', 'lfs.convert', 'lfs.evaluate'],
 'conformance': {'status': 'not_run', 'suite': 'sfmapi-bench'},
 'description': '3D Gaussian Splatting plugin for LichtFeld Studio headless training, conversion, '
                'and export through the sfmapi radiance-field contract.',
 'display_name': 'LichtFeld Studio',
 'entry_points': ['sfmapi_lfs.plugin:plugin'],
 'github_url': 'https://github.com/SFMAPI/sfmapi_lfs.git',
 'licenses': [{'name': 'Apache-2.0'}],
 'package_name': 'sfmapi-lfs',
 'plugin_id': 'lfs',
 'providers': [{'backend_actions': ['lfs.*'],
                'capabilities': ['radiance.train',
                                 'radiance.evaluate',
                                 'radiance.metrics.psnr',
                                 'radiance.metrics.ssim'],
                'display_name': 'LichtFeld Studio',
                'priority_hint': 74,
                'provider_id': 'lfs'}],
 'runtime_modes': {'container_service': {'cache': {'path': '/sfmapi/cache',
                                                   'policy': 'read_write',
                                                   'scope': 'plugin'},
                                         'execution': {'artifact_collection': True,
                                                       'env': ['CUDA_VISIBLE_DEVICES',
                                                               'NVIDIA_VISIBLE_DEVICES',
                                                               'NVIDIA_DRIVER_CAPABILITIES'],
                                                       'gpu': 'required',
                                                       'log_collection': 'both',
                                                       'mounts': {'input_path': '/sfmapi/input',
                                                                  'log_path': '/sfmapi/logs',
                                                                  'output_path': '/sfmapi/output',
                                                                  'work_path': '/sfmapi/work'},
                                                       'path': '/execute',
                                                       'retry': {'backoff_seconds': 0,
                                                                 'max_attempts': 1},
                                                       'secrets': [],
                                                       'shutdown_timeout_seconds': 30,
                                                       'timeout_seconds': 86400},
                                         'healthcheck': {'path': '/healthz', 'timeout_seconds': 5},
                                         'image': {'build': {'args': {'SFMAPI_LFS_REF': 'master'},
                                                             'context': 'https://github.com/SFMAPI/sfmapi_lfs.git',
                                                             'dockerfile': 'Dockerfile',
                                                             'ref': 'master',
                                                             'source': 'git'}},
                                         'object_store': {'input_prefix': 'lfs/input/',
                                                          'output_prefix': 'lfs/output/',
                                                          'url_env': 'SFMAPI_PLUGIN_OBJECT_STORE_URL'},
                                         'protocol': 'sfmapi-plugin-http-v1',
                                         'protocol_version': '1.1',
                                         'provenance': {'image_digest_required': False,
                                                        'source_revision': 'master'},
                                         'service': {'default_url': 'http://127.0.0.1:8095',
                                                     'url_env': 'SFMAPI_LFS_SERVICE_URL'}},
                   'docker': {'build_context': 'https://github.com/SFMAPI/sfmapi_lfs.git',
                              'image': None},
                   'external_tool': None,
                   'uv': {'package': 'sfmapi-lfs',
                          'ref': 'master',
                          'source': 'git',
                          'url': 'https://github.com/SFMAPI/sfmapi_lfs.git'}},
 'trust_tier': 'community',
 'upstream_projects': [{'license': None,
                        'name': 'LichtFeld Studio',
                        'url': 'https://github.com/MrNeRF/LichtFeld-Studio'}]}


# LFS integrates via container_service rather than registering an
# in-process backend factory, so we use the canonical Plugin's
# manifest-only mode (backend_name + backend_factory default to None
# and register() no-ops). `Plugin` stays exported under the same name.
from sfmapi.backends import Plugin  # noqa: E402

plugin = Plugin(manifest=MANIFEST)

__all__ = ["MANIFEST", "Plugin", "plugin"]
